name: Docker Image CI

on:
  push:
    branches: "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/inbuscapapp:latest
      -  
        name: connect ssh
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            docker stop ${{ secrets.CNAME }}
            docker rm ${{ secrets.CNAME }}
            docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/inbuscapapp
            docker run --name ${{ secrets.CNAME }} -p 80:1323 -d -e DBHost=${{secrets.DBHOST}} -e DBPort=3306 -e DBUsername=${{secrets.DBUSERNAME}} -e DBName=${{secrets.DBNAME}} -e DBPassword=${{secrets.DBPASSWORD}} -e Cloudinary_API_Key=${{secrets.Cloudinary_API_Key}} -e Cloudinary_API_Secret=${{secrets.Cloudinary_API_Secret}} -e JWT_SECRET=${{secrets.JWT_SECRET}} 	-e MIDTRANS_SERVER_KEY=${{secrets.MIDTRANS_SERVER_KEY}} ${{ secrets.DOCKERHUB_USERNAME }}/inbuscapapp
